-- WEBPRISM Initial Schema Migration
-- This creates all tables for the WEBPRISM application

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- API Specifications Table
CREATE TABLE api_specs (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version VARCHAR(50) NOT NULL,
    base_url VARCHAR(500) NOT NULL,
    spec_data JSONB NOT NULL,
    paths JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for api_specs
CREATE INDEX idx_api_specs_name ON api_specs(name);
CREATE INDEX idx_api_specs_created_at ON api_specs(created_at DESC);

-- Authentication Configurations Table
CREATE TABLE auth_configs (
    spec_id UUID PRIMARY KEY REFERENCES api_specs(id) ON DELETE CASCADE,
    auth_type VARCHAR(50) NOT NULL,
    encrypted_credentials BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Health Check Records Table
CREATE TABLE health_checks (
    id UUID PRIMARY KEY,
    spec_id UUID NOT NULL REFERENCES api_specs(id) ON DELETE CASCADE,
    check_url VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_time_ms INT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    error_message TEXT,

    CONSTRAINT chk_status CHECK (status IN ('UP', 'DOWN', 'DEGRADED'))
);

-- Create index for health_checks
CREATE INDEX idx_health_checks_spec_id_checked_at ON health_checks(spec_id, checked_at DESC);

-- Comments for documentation
COMMENT ON TABLE api_specs IS 'Stores OpenAPI specifications uploaded by users';
COMMENT ON TABLE auth_configs IS 'Stores encrypted authentication configurations for APIs';
COMMENT ON TABLE health_checks IS 'Stores health check history for monitored APIs';

COMMENT ON COLUMN api_specs.id IS 'UUID generated by application layer to avoid distributed conflicts';
COMMENT ON COLUMN api_specs.spec_data IS 'Full OpenAPI specification in JSONB format';
COMMENT ON COLUMN api_specs.paths IS 'Parsed API paths and operations (cached to avoid re-parsing)';
COMMENT ON COLUMN auth_configs.encrypted_credentials IS 'AES-256-GCM encrypted credentials';
COMMENT ON COLUMN health_checks.response_time_ms IS 'Response time in milliseconds';
