#!/bin/bash
# MCP 測試腳本

echo "==================================="
echo "WEBPRISM MCP 測試指南"
echo "==================================="
echo ""
echo "已完成準備:"
echo "  ✓ MCP server 編譯完成: ./bin/webprism-mcp"
echo "  ✓ PostgreSQL 已啟動（本地）"
echo "  ✓ 環境變數已配置: .env"
echo "  ✓ MCP Inspector 已安裝"
echo ""
echo "==================================="
echo "啟動 MCP Inspector 測試"
echo "==================================="
echo ""
echo "執行以下命令啟動 MCP Inspector:"
echo ""
echo "npx @modelcontextprotocol/inspector ./bin/webprism-mcp"
echo ""
echo "==================================="
echo "預期結果"
echo "==================================="
echo ""
echo "1. MCP Inspector 會開啟瀏覽器視窗"
echo "2. 連線到 MCP server"
echo "3. 應該會看到 6 個工具:"
echo "   - upload_api_spec"
echo "   - list_api_specs"
echo "   - get_api_spec"
echo "   - set_auth"
echo "   - call_api"
echo "   - health_check"
echo ""
echo "==================================="
echo "測試步驟"
echo "==================================="
echo ""
echo "1. 在 Inspector 中點擊 'tools/list' 查看所有工具"
echo "2. 驗證是否有 6 個工具被列出"
echo "3. 檢查每個工具的 schema 是否正確"
echo ""
