package output

import (
	"context"

	"github.com/ChangChunCheng/webprism/internal/domain/model"
)

// HealthRepository defines the output port for health check record persistence.
// This interface is implemented by storage adapters (PostgreSQL, Memory, etc.).
type HealthRepository interface {
	// Create stores a new health check record.
	// The health.ID must be a valid UUID generated by the caller.
	// Returns an error if storage fails.
	Create(ctx context.Context, health *model.HealthCheck) error

	// FindBySpecID retrieves health check records for a spec with pagination.
	// Results are ordered by checked_at DESC (most recent first).
	// Returns a list of HealthCheck records or an empty list if none exist.
	FindBySpecID(ctx context.Context, specID string, limit, offset int) ([]*model.HealthCheck, error)

	// FindLatestBySpecID retrieves the most recent health check for a spec.
	// Returns the latest HealthCheck or nil if no checks exist.
	FindLatestBySpecID(ctx context.Context, specID string) (*model.HealthCheck, error)

	// DeleteBySpecID removes all health check records for a spec.
	// This is typically called when the spec is deleted (cascade delete).
	// Returns the number of records deleted.
	DeleteBySpecID(ctx context.Context, specID string) (int, error)
}
