package output

import (
	"context"

	"github.com/ChangChunCheng/webprism/internal/domain/model"
)

// SpecRepository defines the output port for API Spec persistence operations.
// This interface is implemented by storage adapters (PostgreSQL, Memory, etc.).
type SpecRepository interface {
	// Create stores a new API specification.
	// The spec.ID must be a valid UUID generated by the caller.
	// Returns an error if the spec already exists or if storage fails.
	Create(ctx context.Context, spec *model.APISpec) error

	// FindByID retrieves an API specification by its ID.
	// Returns the APISpec or ErrSpecNotFound if it doesn't exist.
	FindByID(ctx context.Context, id string) (*model.APISpec, error)

	// FindAll retrieves all API specifications with pagination.
	// Results are ordered by created_at DESC.
	// Returns a list of APISpecs or an empty list if none exist.
	FindAll(ctx context.Context, limit, offset int) ([]*model.APISpec, error)

	// Update updates an existing API specification.
	// Only updates the fields: name, version, base_url, spec_data, updated_at.
	// Returns ErrSpecNotFound if the spec doesn't exist.
	Update(ctx context.Context, spec *model.APISpec) error

	// Delete removes an API specification by ID.
	// This should cascade delete related auth configs and health checks.
	// Returns ErrSpecNotFound if the spec doesn't exist.
	Delete(ctx context.Context, id string) error

	// Exists checks if a spec exists by ID.
	// Returns true if exists, false otherwise.
	Exists(ctx context.Context, id string) (bool, error)
}
